ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
	ssid="Yarden"
	psk=bde36409086ec403ca25d5d226e433ace844e74cd3882c8459dd8c4f62f74acf
}

network={
	ssid="Iphone14"
	psk="hrda8775"
	key_mgmt=WPA-PSK
}

network={
	ssid="sc"
	psk="A1ty53dZgK9(dBzaA5*2;"
	key_mgmt=WPA-PSK
}

network={
        ssid="skunki_funki"
        psk="0547407479"
}
